// ============================================================================
// CHUNK 5 — chunk5_data.js
// Complete Muscle Database for Romanian-language Muscle Atrophy Visualization
// 129 muscles across 12 anatomical groups
// ============================================================================

const MUSCLE_DB = [

  // =========================================================================
  // HEAD & NECK — Cap și Gât (19 muscles)
  // =========================================================================

  {
    id: "frontalis",
    name: "Frontalis",
    latin: "Musculus frontalis",
    group: "head",
    groupName: "Cap și Gât",
    location: "front",
    function: "Ridicarea sprâncenelor și formarea ridurilor orizontale pe frunte.",
    atrophyRate: "very-slow",
    strengthLossPerWeek: 0.3,
    atrophyTimeline: { noticeable: 26, significant: 52, severe: 104 },
    deskRisk: 0.05,
    activities: { desk: 0.05, walking: 0.05, cycling: 0.05, strength: 0.1 },
    recovery: { mild: "2-4 săpt.", moderate: "4-8 săpt.", severe: "2-4 luni" },
    exercises: ["Ridicări de sprâncene", "Exerciții de mimică facială"],
    posturalNote: null
  },
  {
    id: "occipitalis",
    name: "Occipitalis",
    latin: "Musculus occipitalis",
    group: "head",
    groupName: "Cap și Gât",
    location: "back",
    function: "Tensionarea scalpului și tragerea posterioară a pielii capului.",
    atrophyRate: "very-slow",
    strengthLossPerWeek: 0.3,
    atrophyTimeline: { noticeable: 26, significant: 52, severe: 104 },
    deskRisk: 0.05,
    activities: { desk: 0.03, walking: 0.03, cycling: 0.03, strength: 0.05 },
    recovery: { mild: "2-4 săpt.", moderate: "4-8 săpt.", severe: "2-4 luni" },
    exercises: ["Exerciții de mimică facială", "Masaj scalp"],
    posturalNote: null
  },
  {
    id: "temporalis",
    name: "Temporalis",
    latin: "Musculus temporalis",
    group: "head",
    groupName: "Cap și Gât",
    location: "both",
    function: "Închiderea mandibulei și masticație. Esențial pentru mestecat.",
    atrophyRate: "very-slow",
    strengthLossPerWeek: 0.3,
    atrophyTimeline: { noticeable: 26, significant: 52, severe: 104 },
    deskRisk: 0.05,
    activities: { desk: 0.15, walking: 0.15, cycling: 0.15, strength: 0.15 },
    recovery: { mild: "2-4 săpt.", moderate: "4-8 săpt.", severe: "2-4 luni" },
    exercises: ["Exerciții de masticație", "Deschidere/închidere mandibulă contra rezistență"],
    posturalNote: null
  },
  {
    id: "masseter",
    name: "Masseter",
    latin: "Musculus masseter",
    group: "head",
    groupName: "Cap și Gât",
    location: "both",
    function: "Cel mai puternic mușchi masticator. Închiderea mandibulei cu forță.",
    atrophyRate: "very-slow",
    strengthLossPerWeek: 0.3,
    atrophyTimeline: { noticeable: 26, significant: 52, severe: 104 },
    deskRisk: 0.05,
    activities: { desk: 0.15, walking: 0.15, cycling: 0.15, strength: 0.15 },
    recovery: { mild: "2-4 săpt.", moderate: "4-8 săpt.", severe: "2-4 luni" },
    exercises: ["Masticație contra rezistență", "Exerciții mandibulare"],
    posturalNote: null
  },
  {
    id: "pterigoidian_medial",
    name: "Pterigoidian Medial",
    latin: "Musculus pterygoideus medialis",
    group: "head",
    groupName: "Cap și Gât",
    location: "both",
    function: "Asistă masticația și mișcarea laterală a mandibulei.",
    atrophyRate: "very-slow",
    strengthLossPerWeek: 0.3,
    atrophyTimeline: { noticeable: 26, significant: 52, severe: 104 },
    deskRisk: 0.05,
    activities: { desk: 0.1, walking: 0.1, cycling: 0.1, strength: 0.1 },
    recovery: { mild: "2-4 săpt.", moderate: "4-8 săpt.", severe: "2-4 luni" },
    exercises: ["Mișcări laterale ale mandibulei", "Exerciții de masticație"],
    posturalNote: null
  },
  {
    id: "pterigoidian_lateral",
    name: "Pterigoidian Lateral",
    latin: "Musculus pterygoideus lateralis",
    group: "head",
    groupName: "Cap și Gât",
    location: "both",
    function: "Deschiderea gurii și protruziunea mandibulei.",
    atrophyRate: "very-slow",
    strengthLossPerWeek: 0.3,
    atrophyTimeline: { noticeable: 26, significant: 52, severe: 104 },
    deskRisk: 0.05,
    activities: { desk: 0.1, walking: 0.1, cycling: 0.1, strength: 0.1 },
    recovery: { mild: "2-4 săpt.", moderate: "4-8 săpt.", severe: "2-4 luni" },
    exercises: ["Deschidere largă a gurii", "Protruzia/retruzia mandibulei"],
    posturalNote: null
  },
  {
    id: "buccinator",
    name: "Buccinator",
    latin: "Musculus buccinator",
    group: "head",
    groupName: "Cap și Gât",
    location: "both",
    function: "Comprimarea obrajilor pentru suflare și asistarea masticației.",
    atrophyRate: "very-slow",
    strengthLossPerWeek: 0.3,
    atrophyTimeline: { noticeable: 26, significant: 52, severe: 104 },
    deskRisk: 0.05,
    activities: { desk: 0.05, walking: 0.05, cycling: 0.05, strength: 0.05 },
    recovery: { mild: "2-4 săpt.", moderate: "4-8 săpt.", severe: "2-4 luni" },
    exercises: ["Umflarea obrajilor", "Exerciții de suflare"],
    posturalNote: null
  },
  {
    id: "orbicularis_oculi",
    name: "Orbicularis Oculi",
    latin: "Musculus orbicularis oculi",
    group: "head",
    groupName: "Cap și Gât",
    location: "front",
    function: "Clipirea și închiderea ochilor. Protecția globului ocular.",
    atrophyRate: "very-slow",
    strengthLossPerWeek: 0.2,
    atrophyTimeline: { noticeable: 30, significant: 60, severe: 120 },
    deskRisk: 0.05,
    activities: { desk: 0.2, walking: 0.2, cycling: 0.2, strength: 0.2 },
    recovery: { mild: "2-4 săpt.", moderate: "4-8 săpt.", severe: "2-4 luni" },
    exercises: ["Clipire puternică", "Închidere strânsă a ochilor"],
    posturalNote: null
  },
  {
    id: "orbicularis_oris",
    name: "Orbicularis Oris",
    latin: "Musculus orbicularis oris",
    group: "head",
    groupName: "Cap și Gât",
    location: "front",
    function: "Închiderea și mișcarea buzelor. Esențial pentru vorbire și mâncat.",
    atrophyRate: "very-slow",
    strengthLossPerWeek: 0.2,
    atrophyTimeline: { noticeable: 30, significant: 60, severe: 120 },
    deskRisk: 0.05,
    activities: { desk: 0.15, walking: 0.15, cycling: 0.15, strength: 0.15 },
    recovery: { mild: "2-4 săpt.", moderate: "4-8 săpt.", severe: "2-4 luni" },
    exercises: ["Exerciții de pronunție", "Rezistența buzelor"],
    posturalNote: null
  },
  {
    id: "sternocleidomastoid",
    name: "Sternocleidomastoid",
    latin: "Musculus sternocleidomastoideus",
    group: "head",
    groupName: "Cap și Gât",
    location: "both",
    function: "Rotația și flexia laterală a capului. Flexia gâtului când acționează bilateral.",
    atrophyRate: "moderate",
    strengthLossPerWeek: 1.8,
    atrophyTimeline: { noticeable: 4, significant: 10, severe: 20 },
    deskRisk: 0.65,
    activities: { desk: 0.3, walking: 0.25, cycling: 0.3, strength: 0.7 },
    recovery: { mild: "2-4 săpt.", moderate: "6-12 săpt.", severe: "3-6 luni" },
    exercises: ["Flexii cervicale", "Rotații contra rezistență", "Chin tucks"],
    posturalNote: "Se scurtează și se suprasolicită la birou din cauza proiecției anterioare a capului. Devine tensionat, nu neapărat atrofiat."
  },
  {
    id: "scalen_anterior",
    name: "Scaleni (Anterior)",
    latin: "Musculus scalenus anterior",
    group: "head",
    groupName: "Cap și Gât",
    location: "front",
    function: "Flexia laterală a gâtului și asistarea inspirației.",
    atrophyRate: "slow",
    strengthLossPerWeek: 0.8,
    atrophyTimeline: { noticeable: 12, significant: 24, severe: 48 },
    deskRisk: 0.4,
    activities: { desk: 0.15, walking: 0.15, cycling: 0.2, strength: 0.6 },
    recovery: { mild: "2-4 săpt.", moderate: "4-8 săpt.", severe: "3-6 luni" },
    exercises: ["Flexie laterală contra rezistență", "Stretching cervical"],
    posturalNote: "Pot deveni tensionați la birou din cauza posturii proaste a capului."
  },
  {
    id: "scalen_mijlociu",
    name: "Scaleni (Mijlociu)",
    latin: "Musculus scalenus medius",
    group: "head",
    groupName: "Cap și Gât",
    location: "both",
    function: "Flexia laterală a gâtului și stabilizarea cervicală.",
    atrophyRate: "slow",
    strengthLossPerWeek: 0.8,
    atrophyTimeline: { noticeable: 12, significant: 24, severe: 48 },
    deskRisk: 0.4,
    activities: { desk: 0.15, walking: 0.15, cycling: 0.2, strength: 0.6 },
    recovery: { mild: "2-4 săpt.", moderate: "4-8 săpt.", severe: "3-6 luni" },
    exercises: ["Flexie laterală contra rezistență", "Stretching cervical"],
    posturalNote: "Pot deveni tensionați la birou din cauza posturii proaste a capului."
  },
  {
    id: "scalen_posterior",
    name: "Scaleni (Posterior)",
    latin: "Musculus scalenus posterior",
    group: "head",
    groupName: "Cap și Gât",
    location: "back",
    function: "Flexia laterală a gâtului și stabilizarea vertebrelor cervicale.",
    atrophyRate: "slow",
    strengthLossPerWeek: 0.8,
    atrophyTimeline: { noticeable: 12, significant: 24, severe: 48 },
    deskRisk: 0.4,
    activities: { desk: 0.15, walking: 0.15, cycling: 0.2, strength: 0.6 },
    recovery: { mild: "2-4 săpt.", moderate: "4-8 săpt.", severe: "3-6 luni" },
    exercises: ["Flexie laterală contra rezistență", "Stretching cervical"],
    posturalNote: "Pot deveni tensionați la birou din cauza posturii proaste a capului."
  },
  {
    id: "platysma",
    name: "Platysma",
    latin: "Platysma",
    group: "head",
    groupName: "Cap și Gât",
    location: "front",
    function: "Tensionarea pielii gâtului și tragerea inferioară a buzei.",
    atrophyRate: "very-slow",
    strengthLossPerWeek: 0.3,
    atrophyTimeline: { noticeable: 26, significant: 52, severe: 104 },
    deskRisk: 0.1,
    activities: { desk: 0.03, walking: 0.05, cycling: 0.05, strength: 0.1 },
    recovery: { mild: "2-4 săpt.", moderate: "4-8 săpt.", severe: "2-4 luni" },
    exercises: ["Exerciții de mimică", "Deschiderea gurii cu rezistență"],
    posturalNote: null
  },
  {
    id: "digastric",
    name: "Digastric",
    latin: "Musculus digastricus",
    group: "head",
    groupName: "Cap și Gât",
    location: "front",
    function: "Deschiderea gurii și deprimarea mandibulei.",
    atrophyRate: "very-slow",
    strengthLossPerWeek: 0.3,
    atrophyTimeline: { noticeable: 26, significant: 52, severe: 104 },
    deskRisk: 0.05,
    activities: { desk: 0.1, walking: 0.1, cycling: 0.1, strength: 0.1 },
    recovery: { mild: "2-4 săpt.", moderate: "4-8 săpt.", severe: "2-4 luni" },
    exercises: ["Deschiderea gurii contra rezistență", "Exerciții mandibulare"],
    posturalNote: null
  },
  {
    id: "longus_colli",
    name: "Longus Colli",
    latin: "Musculus longus colli",
    group: "head",
    groupName: "Cap și Gât",
    location: "front",
    function: "Flexia cervicală profundă și stabilizarea coloanei cervicale.",
    atrophyRate: "moderate",
    strengthLossPerWeek: 2.0,
    atrophyTimeline: { noticeable: 4, significant: 10, severe: 20 },
    deskRisk: 0.85,
    activities: { desk: 0.05, walking: 0.2, cycling: 0.15, strength: 0.8 },
    recovery: { mild: "2-4 săpt.", moderate: "6-12 săpt.", severe: "3-6 luni" },
    exercises: ["Chin tucks", "Flexie craniocervicală", "Activare flexori profunzi"],
    posturalNote: "Extrem de vulnerabil la atrofie de birou. Slăbirea sa cauzează proiecția anterioară a capului și dureri cervicale cronice."
  },
  {
    id: "splenius_capitis",
    name: "Splenius Capitis",
    latin: "Musculus splenius capitis",
    group: "head",
    groupName: "Cap și Gât",
    location: "back",
    function: "Extensia și rotația capului. Menținerea capului în poziție dreaptă.",
    atrophyRate: "slow",
    strengthLossPerWeek: 0.8,
    atrophyTimeline: { noticeable: 12, significant: 24, severe: 48 },
    deskRisk: 0.4,
    activities: { desk: 0.2, walking: 0.25, cycling: 0.2, strength: 0.7 },
    recovery: { mild: "2-4 săpt.", moderate: "4-8 săpt.", severe: "3-6 luni" },
    exercises: ["Extensii cervicale", "Retracție cervicală"],
    posturalNote: "Suprasolicitat la birou pentru a compensa proiecția anterioară a capului."
  },
  {
    id: "splenius_cervicis",
    name: "Splenius Cervicis",
    latin: "Musculus splenius cervicis",
    group: "head",
    groupName: "Cap și Gât",
    location: "back",
    function: "Extensia și rotația gâtului.",
    atrophyRate: "slow",
    strengthLossPerWeek: 0.8,
    atrophyTimeline: { noticeable: 12, significant: 24, severe: 48 },
    deskRisk: 0.4,
    activities: { desk: 0.2, walking: 0.25, cycling: 0.2, strength: 0.7 },
    recovery: { mild: "2-4 săpt.", moderate: "4-8 săpt.", severe: "3-6 luni" },
    exercises: ["Extensii cervicale", "Retracție cervicală"],
    posturalNote: "Suprasolicitat la birou împreună cu splenius capitis."
  },
  {
    id: "semispinalis_capitis",
    name: "Semispinalis Capitis",
    latin: "Musculus semispinalis capitis",
    group: "head",
    groupName: "Cap și Gât",
    location: "back",
    function: "Extensia capului și menținerea posturii cervicale.",
    atrophyRate: "slow",
    strengthLossPerWeek: 0.8,
    atrophyTimeline: { noticeable: 12, significant: 24, severe: 48 },
    deskRisk: 0.45,
    activities: { desk: 0.2, walking: 0.25, cycling: 0.2, strength: 0.7 },
    recovery: { mild: "2-4 săpt.", moderate: "4-8 săpt.", severe: "3-6 luni" },
    exercises: ["Extensii cervicale", "Chin tucks", "Retracție cervicală"],
    posturalNote: "Suprasolicitat la birou pentru susținerea capului în postură flexată."
  },

  // =========================================================================
  // SHOULDERS — Umeri (15 muscles)
  // =========================================================================

  {
    id: "deltoid_anterior",
    name: "Deltoid Anterior",
    latin: "Musculus deltoideus (pars clavicularis)",
    group: "shoulder",
    groupName: "Umeri",
    location: "front",
    function: "Ridicarea brațului înainte (flexia umărului) și rotația internă.",
    atrophyRate: "moderate",
    strengthLossPerWeek: 2.0,
    atrophyTimeline: { noticeable: 4, significant: 10, severe: 20 },
    deskRisk: 0.55,
    activities: { desk: 0.1, walking: 0.15, cycling: 0.2, strength: 0.9 },
    recovery: { mild: "2-4 săpt.", moderate: "6-12 săpt.", severe: "3-6 luni" },
    exercises: ["Ridicări frontale", "Presa de umăr", "Flotări"],
    posturalNote: "Ușor activat la birou prin menținerea brațelor pe birou. Atrofie mai lentă decât deltoidul posterior."
  },
  {
    id: "deltoid_lateral",
    name: "Deltoid Lateral",
    latin: "Musculus deltoideus (pars acromialis)",
    group: "shoulder",
    groupName: "Umeri",
    location: "both",
    function: "Ridicarea brațului lateral (abducția umărului).",
    atrophyRate: "rapid",
    strengthLossPerWeek: 2.8,
    atrophyTimeline: { noticeable: 3, significant: 8, severe: 16 },
    deskRisk: 0.75,
    activities: { desk: 0.05, walking: 0.1, cycling: 0.1, strength: 0.95 },
    recovery: { mild: "2-4 săpt.", moderate: "6-12 săpt.", severe: "3-6 luni" },
    exercises: ["Ridicări laterale", "Presa de umăr", "Abducție cu banda elastică"],
    posturalNote: "Neactivat în poziția de birou. Pierderea forței afectează capacitatea de ridicare a obiectelor."
  },
  {
    id: "deltoid_posterior",
    name: "Deltoid Posterior",
    latin: "Musculus deltoideus (pars spinalis)",
    group: "shoulder",
    groupName: "Umeri",
    location: "back",
    function: "Tragerea brațului înapoi (extensia umărului) și rotația externă.",
    atrophyRate: "rapid",
    strengthLossPerWeek: 3.0,
    atrophyTimeline: { noticeable: 2, significant: 6, severe: 14 },
    deskRisk: 0.85,
    activities: { desk: 0.02, walking: 0.1, cycling: 0.05, strength: 0.9 },
    recovery: { mild: "2-4 săpt.", moderate: "6-12 săpt.", severe: "3-6 luni" },
    exercises: ["Reverse flyes", "Face pulls", "Ramat la cablu"],
    posturalNote: "Extrem de vulnerabil. Slăbirea sa contribuie direct la umerii rotunjiți de la birou."
  },
  {
    id: "supraspinatus",
    name: "Supraspinatus",
    latin: "Musculus supraspinatus",
    group: "shoulder",
    groupName: "Umeri",
    location: "back",
    function: "Inițierea abducției brațului și stabilizarea articulației umărului.",
    atrophyRate: "moderate",
    strengthLossPerWeek: 2.0,
    atrophyTimeline: { noticeable: 4, significant: 10, severe: 20 },
    deskRisk: 0.6,
    activities: { desk: 0.05, walking: 0.1, cycling: 0.1, strength: 0.85 },
    recovery: { mild: "2-4 săpt.", moderate: "6-12 săpt.", severe: "3-6 luni" },
    exercises: ["Ridicări laterale parțiale", "Rotații externe", "Exerciții cu bandă elastică"],
    posturalNote: "Risc de impingement la birou. Slăbirea crește vulnerabilitatea la leziuni de umăr."
  },
  {
    id: "infraspinatus",
    name: "Infraspinatus",
    latin: "Musculus infraspinatus",
    group: "shoulder",
    groupName: "Umeri",
    location: "back",
    function: "Rotația externă a brațului și stabilizarea posterioară a umărului.",
    atrophyRate: "rapid",
    strengthLossPerWeek: 2.5,
    atrophyTimeline: { noticeable: 3, significant: 8, severe: 16 },
    deskRisk: 0.8,
    activities: { desk: 0.03, walking: 0.1, cycling: 0.05, strength: 0.9 },
    recovery: { mild: "2-4 săpt.", moderate: "6-12 săpt.", severe: "3-6 luni" },
    exercises: ["Rotații externe cu gantera", "Face pulls", "Rotații externe cu bandă"],
    posturalNote: "Critic pentru sănătatea umărului. Slăbirea sa duce la dominanța rotației interne la birou."
  },
  {
    id: "teres_minor",
    name: "Teres Minor",
    latin: "Musculus teres minor",
    group: "shoulder",
    groupName: "Umeri",
    location: "back",
    function: "Rotația externă a brațului și stabilizarea umărului.",
    atrophyRate: "rapid",
    strengthLossPerWeek: 2.5,
    atrophyTimeline: { noticeable: 3, significant: 8, severe: 16 },
    deskRisk: 0.75,
    activities: { desk: 0.03, walking: 0.1, cycling: 0.05, strength: 0.85 },
    recovery: { mild: "2-4 săpt.", moderate: "6-12 săpt.", severe: "3-6 luni" },
    exercises: ["Rotații externe", "Face pulls", "Band pull-aparts"],
    posturalNote: "Se slăbește împreună cu infraspinatus, contribuind la instabilitatea umărului."
  },
  {
    id: "teres_major",
    name: "Teres Major",
    latin: "Musculus teres major",
    group: "shoulder",
    groupName: "Umeri",
    location: "back",
    function: "Adducția și rotația internă a brațului. Asistă extensia umărului.",
    atrophyRate: "rapid",
    strengthLossPerWeek: 2.5,
    atrophyTimeline: { noticeable: 3, significant: 8, severe: 16 },
    deskRisk: 0.7,
    activities: { desk: 0.03, walking: 0.1, cycling: 0.1, strength: 0.85 },
    recovery: { mild: "2-4 săpt.", moderate: "6-12 săpt.", severe: "3-6 luni" },
    exercises: ["Tracțiuni", "Ramat cu gantera", "Pulldown la cablu"],
    posturalNote: null
  },
  {
    id: "subscapularis",
    name: "Subscapularis",
    latin: "Musculus subscapularis",
    group: "shoulder",
    groupName: "Umeri",
    location: "front",
    function: "Rotația internă a umărului și stabilizarea articulației glenoumerale.",
    atrophyRate: "moderate",
    strengthLossPerWeek: 1.8,
    atrophyTimeline: { noticeable: 5, significant: 12, severe: 22 },
    deskRisk: 0.5,
    activities: { desk: 0.08, walking: 0.1, cycling: 0.1, strength: 0.85 },
    recovery: { mild: "2-4 săpt.", moderate: "6-12 săpt.", severe: "3-6 luni" },
    exercises: ["Rotații interne cu bandă", "Rotații interne la cablu"],
    posturalNote: "Tinde să se scurteze la birou din cauza poziției brațelor în rotație internă."
  },
  {
    id: "levator_scapulae",
    name: "Levator Scapulae",
    latin: "Musculus levator scapulae",
    group: "shoulder",
    groupName: "Umeri",
    location: "back",
    function: "Ridicarea omoplatului și flexia laterală a gâtului.",
    atrophyRate: "slow",
    strengthLossPerWeek: 0.8,
    atrophyTimeline: { noticeable: 12, significant: 24, severe: 48 },
    deskRisk: 0.6,
    activities: { desk: 0.35, walking: 0.15, cycling: 0.2, strength: 0.7 },
    recovery: { mild: "2-4 săpt.", moderate: "6-12 săpt.", severe: "3-6 luni" },
    exercises: ["Shrugs", "Stretching cervical lateral", "Exerciții de relaxare umeri"],
    posturalNote: "Se suprasolicită și se contractă la birou. Sursă frecventă de durere cervicală și cefalee de tensiune."
  },
  {
    id: "romboid_major",
    name: "Romboid Major",
    latin: "Musculus rhomboideus major",
    group: "shoulder",
    groupName: "Umeri",
    location: "back",
    function: "Retracția omoplatului (tragerea spre coloană) și stabilizarea scapulei.",
    atrophyRate: "rapid",
    strengthLossPerWeek: 2.8,
    atrophyTimeline: { noticeable: 3, significant: 7, severe: 14 },
    deskRisk: 0.85,
    activities: { desk: 0.03, walking: 0.15, cycling: 0.1, strength: 0.9 },
    recovery: { mild: "2-4 săpt.", moderate: "6-12 săpt.", severe: "3-6 luni" },
    exercises: ["Ramat cu bara", "Face pulls", "Band pull-aparts", "Ramat la cablu"],
    posturalNote: "Critic pentru postura la birou. Slăbirea romboidului duce direct la umeri rotunjiți și cifoză toracică."
  },
  {
    id: "romboid_minor",
    name: "Romboid Minor",
    latin: "Musculus rhomboideus minor",
    group: "shoulder",
    groupName: "Umeri",
    location: "back",
    function: "Retracția omoplatului și asistarea stabilizării scapulare.",
    atrophyRate: "rapid",
    strengthLossPerWeek: 2.8,
    atrophyTimeline: { noticeable: 3, significant: 7, severe: 14 },
    deskRisk: 0.85,
    activities: { desk: 0.03, walking: 0.15, cycling: 0.1, strength: 0.9 },
    recovery: { mild: "2-4 săpt.", moderate: "6-12 săpt.", severe: "3-6 luni" },
    exercises: ["Ramat cu bara", "Face pulls", "Band pull-aparts"],
    posturalNote: "Se slăbește împreună cu romboidul major, contribuind la protracția scapulară."
  },
  {
    id: "serratus_anterior",
    name: "Serratus Anterior",
    latin: "Musculus serratus anterior",
    group: "shoulder",
    groupName: "Umeri",
    location: "both",
    function: "Protracția și stabilizarea omoplatului pe cutia toracică. Esențial pentru ridicarea brațelor deasupra capului.",
    atrophyRate: "rapid",
    strengthLossPerWeek: 2.8,
    atrophyTimeline: { noticeable: 3, significant: 7, severe: 14 },
    deskRisk: 0.8,
    activities: { desk: 0.05, walking: 0.1, cycling: 0.15, strength: 0.9 },
    recovery: { mild: "2-4 săpt.", moderate: "6-12 săpt.", severe: "3-6 luni" },
    exercises: ["Serratus push-ups", "Serratus punch", "Presa overhead", "Scapular push-ups"],
    posturalNote: "Slăbirea cauzează scapula aripă (winging) și dificultăți în ridicarea brațelor. Foarte afectat de sedentarism."
  },
  {
    id: "trapez_superior",
    name: "Trapez Superior",
    latin: "Musculus trapezius (pars descendens)",
    group: "shoulder",
    groupName: "Umeri",
    location: "back",
    function: "Ridicarea umerilor și extensia gâtului. Susținerea centurii scapulare.",
    atrophyRate: "slow",
    strengthLossPerWeek: 0.8,
    atrophyTimeline: { noticeable: 12, significant: 24, severe: 48 },
    deskRisk: 0.3,
    activities: { desk: 0.4, walking: 0.2, cycling: 0.25, strength: 0.85 },
    recovery: { mild: "2-4 săpt.", moderate: "4-8 săpt.", severe: "3-6 luni" },
    exercises: ["Shrugs", "Farmer's walk", "Upright rows"],
    posturalNote: "Paradoxal, nu atrofiază la birou — se suprasolicită. Tensiune cronică din cauza poziției umerilor ridicați la tastatură."
  },
  {
    id: "trapez_mijlociu",
    name: "Trapez Mijlociu",
    latin: "Musculus trapezius (pars transversa)",
    group: "shoulder",
    groupName: "Umeri",
    location: "back",
    function: "Retracția umerilor (tragerea omoplatului spre coloană).",
    atrophyRate: "rapid",
    strengthLossPerWeek: 2.5,
    atrophyTimeline: { noticeable: 3, significant: 8, severe: 16 },
    deskRisk: 0.8,
    activities: { desk: 0.05, walking: 0.15, cycling: 0.1, strength: 0.9 },
    recovery: { mild: "2-4 săpt.", moderate: "6-12 săpt.", severe: "3-6 luni" },
    exercises: ["Face pulls", "Ramat cu bara", "Band pull-aparts", "Reverse flyes"],
    posturalNote: "Foarte vulnerabil la birou. Slăbirea sa permite protracția umerilor și cifoza toracică."
  },
  {
    id: "trapez_inferior",
    name: "Trapez Inferior",
    latin: "Musculus trapezius (pars ascendens)",
    group: "shoulder",
    groupName: "Umeri",
    location: "back",
    function: "Deprimarea și rotația superioară a omoplatului.",
    atrophyRate: "rapid",
    strengthLossPerWeek: 2.5,
    atrophyTimeline: { noticeable: 3, significant: 8, severe: 16 },
    deskRisk: 0.8,
    activities: { desk: 0.03, walking: 0.1, cycling: 0.1, strength: 0.85 },
    recovery: { mild: "2-4 săpt.", moderate: "6-12 săpt.", severe: "3-6 luni" },
    exercises: ["Y-raises", "Presa overhead", "Face pulls cu deprimare scapulară"],
    posturalNote: "Slăbirea sa contribuie la ridicarea compensatorie a umerilor și la disfuncție scapulară."
  },

  // =========================================================================
  // ARMS — Brațe (20 muscles)
  // =========================================================================

  {
    id: "biceps_brahial",
    name: "Biceps Brahial",
    latin: "Musculus biceps brachii",
    group: "arm",
    groupName: "Brațe",
    location: "front",
    function: "Flexia cotului și supinația antebrațului. Mușchi principal al brațului anterior.",
    atrophyRate: "rapid",
    strengthLossPerWeek: 3.0,
    atrophyTimeline: { noticeable: 2, significant: 6, severe: 14 },
    deskRisk: 0.8,
    activities: { desk: 0.05, walking: 0.05, cycling: 0.15, strength: 0.95 },
    recovery: { mild: "2-4 săpt.", moderate: "6-12 săpt.", severe: "3-6 luni" },
    exercises: ["Flexii cu gantera", "Flexii cu bara", "Chin-ups"],
    posturalNote: "Practic neactivat la birou. Unul dintre primii mușchi care pierd masă la sedentari."
  },
  {
    id: "brahialis",
    name: "Brahialis",
    latin: "Musculus brachialis",
    group: "arm",
    groupName: "Brațe",
    location: "front",
    function: "Flexia cotului — cel mai puternic flexor al cotului.",
    atrophyRate: "rapid",
    strengthLossPerWeek: 2.8,
    atrophyTimeline: { noticeable: 3, significant: 7, severe: 14 },
    deskRisk: 0.75,
    activities: { desk: 0.05, walking: 0.05, cycling: 0.15, strength: 0.9 },
    recovery: { mild: "2-4 săpt.", moderate: "6-12 săpt.", severe: "3-6 luni" },
    exercises: ["Flexii hammer", "Flexii cu priză neutră", "Flexii la cablu"],
    posturalNote: null
  },
  {
    id: "brahioradial",
    name: "Brahioradial",
    latin: "Musculus brachioradialis",
    group: "arm",
    groupName: "Brațe",
    location: "front",
    function: "Flexia cotului în poziție neutră. Stabilizarea antebrațului.",
    atrophyRate: "moderate",
    strengthLossPerWeek: 2.0,
    atrophyTimeline: { noticeable: 4, significant: 10, severe: 20 },
    deskRisk: 0.5,
    activities: { desk: 0.2, walking: 0.1, cycling: 0.2, strength: 0.85 },
    recovery: { mild: "2-4 săpt.", moderate: "6-12 săpt.", severe: "3-6 luni" },
    exercises: ["Flexii hammer", "Reverse curls", "Flexii la cablu"],
    posturalNote: "Parțial activat la birou prin utilizarea mouse-ului și tastaturii."
  },
  {
    id: "triceps_brahial",
    name: "Triceps Brahial",
    latin: "Musculus triceps brachii",
    group: "arm",
    groupName: "Brațe",
    location: "back",
    function: "Extensia cotului și extensia umărului (capul lung). Unicul extensor al cotului.",
    atrophyRate: "rapid",
    strengthLossPerWeek: 3.0,
    atrophyTimeline: { noticeable: 2, significant: 6, severe: 14 },
    deskRisk: 0.8,
    activities: { desk: 0.05, walking: 0.05, cycling: 0.15, strength: 0.95 },
    recovery: { mild: "2-4 săpt.", moderate: "6-12 săpt.", severe: "3-6 luni" },
    exercises: ["Extensii triceps", "Flotări", "Dips", "Presa de piept"],
    posturalNote: "Neactivat la birou. Pierde masă și forță rapid la sedentari."
  },
  {
    id: "anconeu",
    name: "Anconeu",
    latin: "Musculus anconeus",
    group: "arm",
    groupName: "Brațe",
    location: "back",
    function: "Asistarea extensiei cotului și stabilizarea articulației cotului.",
    atrophyRate: "moderate",
    strengthLossPerWeek: 1.5,
    atrophyTimeline: { noticeable: 6, significant: 14, severe: 26 },
    deskRisk: 0.5,
    activities: { desk: 0.1, walking: 0.05, cycling: 0.1, strength: 0.7 },
    recovery: { mild: "2-4 săpt.", moderate: "4-8 săpt.", severe: "3-6 luni" },
    exercises: ["Extensii triceps", "Flotări"],
    posturalNote: null
  },
  {
    id: "pronator_teres",
    name: "Pronator Teres",
    latin: "Musculus pronator teres",
    group: "arm",
    groupName: "Brațe",
    location: "front",
    function: "Pronația antebrațului și asistarea flexiei cotului.",
    atrophyRate: "slow",
    strengthLossPerWeek: 1.0,
    atrophyTimeline: { noticeable: 8, significant: 18, severe: 36 },
    deskRisk: 0.35,
    activities: { desk: 0.3, walking: 0.05, cycling: 0.15, strength: 0.75 },
    recovery: { mild: "2-4 săpt.", moderate: "4-8 săpt.", severe: "3-6 luni" },
    exercises: ["Pronații cu gantera", "Rotații ale antebrațului"],
    posturalNote: "Activat la birou prin tastare în poziție de pronație. Risc de suprasolicitare."
  },
  {
    id: "pronator_quadratus",
    name: "Pronator Quadratus",
    latin: "Musculus pronator quadratus",
    group: "arm",
    groupName: "Brațe",
    location: "front",
    function: "Pronația antebrațului — pronatorul principal.",
    atrophyRate: "slow",
    strengthLossPerWeek: 1.0,
    atrophyTimeline: { noticeable: 8, significant: 18, severe: 36 },
    deskRisk: 0.35,
    activities: { desk: 0.3, walking: 0.05, cycling: 0.15, strength: 0.75 },
    recovery: { mild: "2-4 săpt.", moderate: "4-8 săpt.", severe: "3-6 luni" },
    exercises: ["Pronații cu gantera", "Rotații ale antebrațului contra rezistență"],
    posturalNote: null
  },
  {
    id: "supinator",
    name: "Supinator",
    latin: "Musculus supinator",
    group: "arm",
    groupName: "Brațe",
    location: "back",
    function: "Supinația antebrațului (rotația externă).",
    atrophyRate: "moderate",
    strengthLossPerWeek: 1.5,
    atrophyTimeline: { noticeable: 6, significant: 14, severe: 26 },
    deskRisk: 0.45,
    activities: { desk: 0.15, walking: 0.05, cycling: 0.1, strength: 0.8 },
    recovery: { mild: "2-4 săpt.", moderate: "4-8 săpt.", severe: "3-6 luni" },
    exercises: ["Supinații cu gantera", "Flexii biceps cu supinație"],
    posturalNote: "Subactivat la birou deoarece tastatura impune pronație constantă."
  },
  {
    id: "flexor_carpi_radialis",
    name: "Flexor Carpi Radialis",
    latin: "Musculus flexor carpi radialis",
    group: "arm",
    groupName: "Brațe",
    location: "front",
    function: "Flexia și abducția (deviația radială) a încheieturii.",
    atrophyRate: "slow",
    strengthLossPerWeek: 0.8,
    atrophyTimeline: { noticeable: 10, significant: 22, severe: 44 },
    deskRisk: 0.3,
    activities: { desk: 0.35, walking: 0.05, cycling: 0.2, strength: 0.8 },
    recovery: { mild: "2-4 săpt.", moderate: "4-8 săpt.", severe: "3-6 luni" },
    exercises: ["Flexii ale încheieturii", "Wrist curls cu gantera"],
    posturalNote: "Activat la tastare. Risc de tendinită și sindrom de tunel carpian la utilizare excesivă."
  },
  {
    id: "flexor_carpi_ulnaris",
    name: "Flexor Carpi Ulnaris",
    latin: "Musculus flexor carpi ulnaris",
    group: "arm",
    groupName: "Brațe",
    location: "front",
    function: "Flexia și deviația ulnară a încheieturii.",
    atrophyRate: "slow",
    strengthLossPerWeek: 0.8,
    atrophyTimeline: { noticeable: 10, significant: 22, severe: 44 },
    deskRisk: 0.3,
    activities: { desk: 0.35, walking: 0.05, cycling: 0.2, strength: 0.8 },
    recovery: { mild: "2-4 săpt.", moderate: "4-8 săpt.", severe: "3-6 luni" },
    exercises: ["Flexii ale încheieturii", "Wrist curls"],
    posturalNote: "Activat la tastare. Suprasolicitare posibilă la utilizare intensivă a tastaturii."
  },
  {
    id: "palmaris_longus",
    name: "Palmaris Longus",
    latin: "Musculus palmaris longus",
    group: "arm",
    groupName: "Brațe",
    location: "front",
    function: "Flexia încheieturii și tensionarea fasciei palmare. Absent la ~14% din populație.",
    atrophyRate: "slow",
    strengthLossPerWeek: 0.8,
    atrophyTimeline: { noticeable: 10, significant: 22, severe: 44 },
    deskRisk: 0.25,
    activities: { desk: 0.3, walking: 0.05, cycling: 0.15, strength: 0.7 },
    recovery: { mild: "2-4 săpt.", moderate: "4-8 săpt.", severe: "3-6 luni" },
    exercises: ["Flexii ale încheieturii", "Strângere de minge"],
    posturalNote: null
  },
  {
    id: "flexor_digitorum_superficialis",
    name: "Flexor Digitorum Superficialis",
    latin: "Musculus flexor digitorum superficialis",
    group: "arm",
    groupName: "Brațe",
    location: "front",
    function: "Flexia articulațiilor interfalangiene proximale ale degetelor 2-5.",
    atrophyRate: "slow",
    strengthLossPerWeek: 0.8,
    atrophyTimeline: { noticeable: 10, significant: 22, severe: 44 },
    deskRisk: 0.25,
    activities: { desk: 0.4, walking: 0.05, cycling: 0.2, strength: 0.8 },
    recovery: { mild: "2-4 săpt.", moderate: "4-8 săpt.", severe: "3-6 luni" },
    exercises: ["Strângere de minge", "Gripper exerciții", "Flexii degete cu bandă"],
    posturalNote: "Foarte activ la tastare. Suprasolicitarea poate duce la tendinită."
  },
  {
    id: "flexor_digitorum_profundus",
    name: "Flexor Digitorum Profundus",
    latin: "Musculus flexor digitorum profundus",
    group: "arm",
    groupName: "Brațe",
    location: "front",
    function: "Flexia articulațiilor interfalangiene distale ale degetelor. Singura forță de flexie a falangei distale.",
    atrophyRate: "slow",
    strengthLossPerWeek: 0.8,
    atrophyTimeline: { noticeable: 10, significant: 22, severe: 44 },
    deskRisk: 0.25,
    activities: { desk: 0.4, walking: 0.05, cycling: 0.2, strength: 0.8 },
    recovery: { mild: "2-4 săpt.", moderate: "4-8 săpt.", severe: "3-6 luni" },
    exercises: ["Strângere de minge", "Dead hangs", "Escaladă"],
    posturalNote: "Foarte activ la tastare. Contribuie la oboseala mâinii la programatori."
  },
  {
    id: "flexor_pollicis_longus",
    name: "Flexor Pollicis Longus",
    latin: "Musculus flexor pollicis longus",
    group: "arm",
    groupName: "Brațe",
    location: "front",
    function: "Flexia falangei distale a policelui. Esențial pentru prinderea de precizie.",
    atrophyRate: "slow",
    strengthLossPerWeek: 0.8,
    atrophyTimeline: { noticeable: 10, significant: 22, severe: 44 },
    deskRisk: 0.25,
    activities: { desk: 0.35, walking: 0.05, cycling: 0.15, strength: 0.75 },
    recovery: { mild: "2-4 săpt.", moderate: "4-8 săpt.", severe: "3-6 luni" },
    exercises: ["Flexii police", "Strângere de minge", "Pinch grip"],
    posturalNote: "Activat la utilizarea mouse-ului și tastaturii. Risc de tendinită la police (De Quervain)."
  },
  {
    id: "extensor_carpi_radialis_longus",
    name: "Extensor Carpi Radialis Longus",
    latin: "Musculus extensor carpi radialis longus",
    group: "arm",
    groupName: "Brațe",
    location: "back",
    function: "Extensia și deviația radială a încheieturii.",
    atrophyRate: "slow",
    strengthLossPerWeek: 0.8,
    atrophyTimeline: { noticeable: 10, significant: 22, severe: 44 },
    deskRisk: 0.35,
    activities: { desk: 0.35, walking: 0.05, cycling: 0.2, strength: 0.8 },
    recovery: { mild: "2-4 săpt.", moderate: "4-8 săpt.", severe: "3-6 luni" },
    exercises: ["Extensii ale încheieturii", "Reverse wrist curls"],
    posturalNote: "Menține încheietura extinsă la tastatură. Risc de epicondilită laterală (cotul tenismenului)."
  },
  {
    id: "extensor_carpi_radialis_brevis",
    name: "Extensor Carpi Radialis Brevis",
    latin: "Musculus extensor carpi radialis brevis",
    group: "arm",
    groupName: "Brațe",
    location: "back",
    function: "Extensia și stabilizarea încheieturii. Cel mai frecvent implicat în epicondilită laterală.",
    atrophyRate: "slow",
    strengthLossPerWeek: 0.8,
    atrophyTimeline: { noticeable: 10, significant: 22, severe: 44 },
    deskRisk: 0.35,
    activities: { desk: 0.35, walking: 0.05, cycling: 0.2, strength: 0.8 },
    recovery: { mild: "2-4 săpt.", moderate: "4-8 săpt.", severe: "3-6 luni" },
    exercises: ["Extensii ale încheieturii", "Reverse wrist curls"],
    posturalNote: "Cel mai vulnerabil mușchi la cotul tenismenului din cauza tastării prelungite."
  },
  {
    id: "extensor_carpi_ulnaris",
    name: "Extensor Carpi Ulnaris",
    latin: "Musculus extensor carpi ulnaris",
    group: "arm",
    groupName: "Brațe",
    location: "back",
    function: "Extensia și deviația ulnară a încheieturii.",
    atrophyRate: "slow",
    strengthLossPerWeek: 0.8,
    atrophyTimeline: { noticeable: 10, significant: 22, severe: 44 },
    deskRisk: 0.3,
    activities: { desk: 0.3, walking: 0.05, cycling: 0.2, strength: 0.8 },
    recovery: { mild: "2-4 săpt.", moderate: "4-8 săpt.", severe: "3-6 luni" },
    exercises: ["Extensii ale încheieturii", "Reverse wrist curls"],
    posturalNote: null
  },
  {
    id: "extensor_digitorum",
    name: "Extensor Digitorum",
    latin: "Musculus extensor digitorum",
    group: "arm",
    groupName: "Brațe",
    location: "back",
    function: "Extensia degetelor 2-5 și asistarea extensiei încheieturii.",
    atrophyRate: "slow",
    strengthLossPerWeek: 0.8,
    atrophyTimeline: { noticeable: 10, significant: 22, severe: 44 },
    deskRisk: 0.3,
    activities: { desk: 0.35, walking: 0.05, cycling: 0.15, strength: 0.8 },
    recovery: { mild: "2-4 săpt.", moderate: "4-8 săpt.", severe: "3-6 luni" },
    exercises: ["Extensii degete cu bandă elastică", "Reverse wrist curls"],
    posturalNote: "Activ la tastare pentru ridicarea degetelor între apăsări. Suprasolicitare posibilă."
  },
  {
    id: "extensor_pollicis_longus",
    name: "Extensor Pollicis Longus",
    latin: "Musculus extensor pollicis longus",
    group: "arm",
    groupName: "Brațe",
    location: "back",
    function: "Extensia falangei distale a policelui și asistarea extensiei încheieturii.",
    atrophyRate: "slow",
    strengthLossPerWeek: 0.8,
    atrophyTimeline: { noticeable: 10, significant: 22, severe: 44 },
    deskRisk: 0.3,
    activities: { desk: 0.3, walking: 0.05, cycling: 0.15, strength: 0.75 },
    recovery: { mild: "2-4 săpt.", moderate: "4-8 săpt.", severe: "3-6 luni" },
    exercises: ["Extensii police contra rezistență", "Exerciții cu bandă pentru degete"],
    posturalNote: "Utilizat la apăsarea space bar-ului și navigare. Risc de tendinită de Quervain."
  },
  {
    id: "abductor_pollicis_longus",
    name: "Abductor Pollicis Longus",
    latin: "Musculus abductor pollicis longus",
    group: "arm",
    groupName: "Brațe",
    location: "back",
    function: "Abducția și extensia policelui. Important pentru deschiderea mâinii.",
    atrophyRate: "slow",
    strengthLossPerWeek: 0.8,
    atrophyTimeline: { noticeable: 10, significant: 22, severe: 44 },
    deskRisk: 0.3,
    activities: { desk: 0.3, walking: 0.05, cycling: 0.15, strength: 0.75 },
    recovery: { mild: "2-4 săpt.", moderate: "4-8 săpt.", severe: "3-6 luni" },
    exercises: ["Abducție police cu bandă", "Exerciții de deschidere mână"],
    posturalNote: "Implicat în mișcarea policelui la utilizarea mouse-ului."
  },

